### PR TITLE
Switching to CodeQL & Dependabot

### PR DESCRIPTION
**Pull request by scherersebastian**
We're moving from Veracode to CodeQL and Dependabot. This switch brings better GitHub integration, at no extra cost, making our security setup more efficient.

What's Changing:

- Better GitHub Fit: Direct integration with GitHub for security scans and dependency updates.
- Free: Both tools are free, cutting costs.
- Centralized Alerts: Findings now appear in the GitHub Security tab for easier management.

Quick Details:

- CodeQL identifies vulnerabilities directly in the code.
- Dependabot keeps our dependencies fresh and secure.

This update streamlines our security and dependency management, directly within GitHub.

---

You have dependabot and codeql already integrated :)

### CODE REVIEW

**Comment by scherersebastian** [comment]
I also removed spotbugs workflow and config.
CodeQL covers static analysis for spotbugs / java.
Of course you can run both - it's your choice.

**Comment by scherersebastian** [comment]
I removed your trivy workflow that scans the IaC.
KICS does a better job at IaC scanning. 
You do not need to run both.

**Comment by jzbmw** [comment]
@scherersebastian bevor the QQ Criteria are not updated, we will not approve this. Please make sure, that the QG Criteria for 24.03 and 24.05 are updated.

**Comment by scherersebastian** [comment]
Interesting, I will take care of this. 
Thanks for your feedback @jzbmw

**Comment by scherersebastian** [comment]
Hello @jzbmw , I have checked our QGs. With Dependabot and CodeQL all QGs can be successfully completed, it is the replacement for Veracode (SCA, SAST).

**Review by ds-jhartmann — APPROVED** [review]

**Pull request merged**
