### PR TITLE
Feature/371 pi13 transfer to tractus x

### PR DESCRIPTION
**Pull request by ds-jhartmann**
## Description

- Add cucumber feature files
- Remove unused cucumber config and features
- Refactor cucumber test workflows
- Refactor tavern test workflows
- Tavern and Cucumber Test reporting is done directly in GitHub
- Add maven profiles for cucumber tests and dash license check

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by ds-jhartmann** [comment]
- Waiting for GH secret to be added https://github.com/eclipse-tractusx/sig-infra/issues/503
- Waiting for Dash IP Lab approval https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15145

**Review by dsmf — APPROVED** [review]
LGTM

**Review by dsmf — APPROVED** [review]
LGTM

**Review by ds-mwesener — APPROVED** [review]
LGTM

**Pull request merged**
